### ISSUE TITLE
사내 게시판 상세 클래스 다이어그램

### ISSUE THREAD

**Issue by AnByoungHyun** [KH-A3/java-programming#24]

**Comment by oni96oni** [comment]
![Image](https://user-images.githubusercontent.com/95541472/181465266-63b013e9-013d-43ce-98c7-83a01a0e07c1.png)

**Comment by AnByoungHyun** [comment]
구글 드라이브에 업로드 하였습니다.

https://drive.google.com/file/d/1XjUXRL-Ei34667B8K1qiJ_TzajSEMHgx/view?usp=sharing
